import type { Filament } from "@/lib/content/schemas";

export const filaments = [
  {
    id: "1",
    name: "White",
    material: "PLA",
    finish: "Matte",
    hex: "#ffffff",
    status: "In Stock",
  },
  {
    id: "2",
    name: "Black",
    material: "PLA",
    finish: "Matte",
    hex: "#000000",
    status: "In Stock",
  },
  {
    id: "3",
    name: "Red",
    material: "PLA",
    finish: "Standard",
    hex: "#ff0000",
    status: "In Stock",
  },
  {
    id: "4",
    name: "Sea Blue",
    material: "PLA",
    finish: "Matte",
    hex: "#00629b",
    status: "In Stock",
  },
  {
    id: "5",
    name: "Black",
    material: "PLA",
    finish: "Standard",
    hex: "#000000",
    status: "In Stock",
  },
  {
    id: "6",
    name: "White",
    material: "PLA",
    finish: "Standard",
    hex: "#ffffff",
    status: "In Stock",
  },
  {
    id: "7",
    name: "Burnt Grey",
    material: "PLA",
    finish: "Matte",
    hex: "#4b4f54",
    status: "In Stock",
  },
  {
    id: "8",
    name: "Dirty Purple",
    material: "PLA",
    finish: "Matte",
    hex: "#7e5475",
    status: "In Stock",
  },
  {
    id: "9",
    name: "Stepped On Orange",
    material: "PLA",
    finish: "Matte",
    hex: "#ff8f1c",
    status: "In Stock",
  },
  {
    id: "10",
    name: "Leaf Green",
    material: "PLA",
    finish: "Matte",
    hex: "#4b9560",
    status: "In Stock",
  },
  {
    id: "11",
    name: "Pink",
    material: "PLA",
    finish: "Standard",
    hex: "#ff80ff",
    status: "In Stock",
  },
  {
    id: "12",
    name: "Grey Marble",
    material: "PLA",
    finish: "Marble",
    hex: "#c0c0c0",
    status: "In Stock",
  },
  {
    id: "13",
    name: "Purple",
    material: "PLA",
    finish: "Silk",
    hex: "#8000ff",
    status: "In Stock",
  },
  {
    id: "14",
    name: "Rainbow Matte",
    material: "PLA",
    finish: "Gradient",
    hex: "#00e5ff",
    status: "In Stock",
  },
] as const satisfies readonly Filament[];
