import Link from "next/link";
import { LegalArticle } from "@/components/legal/LegalArticle";
import { createMetadata } from "@/lib/metadata/create-metadata";

export const metadata = createMetadata({
  title: "Terms and Conditions",
  description: "Clarky3D Terms and Conditions for use of clarky3d.com.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <LegalArticle title="Terms and Conditions" updated="11 August 2026">
      <h2>Agreement to terms</h2>
      <p>
        These Terms of Use constitute a legally binding agreement made between you, whether
        personally or on behalf of an entity (“you”) and Clarky3D (“we”, “us”, or “our”), concerning
        your access to and use of the website{" "}
        <a href="https://clarky3d.com">https://clarky3d.com</a> as well as any other media form,
        media channel, mobile website or mobile application related, linked, or otherwise connected
        thereto (collectively, the “Site”).
      </p>
      <p>
        You agree that by accessing the Site, you have read, understood, and agreed to be bound by
        all of these Terms of Use. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF USE, THEN YOU ARE
        EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY.
      </p>
      <p>
        Clarky3D (“we”, or “us”) also operates a mobile messaging program (the “Program”) subject to
        our <Link href="/sms-terms">SMS Terms</Link>. The Program and our collection and use of your
        personal information are also subject to our <Link href="/privacy">Privacy Policy</Link>. By
        enrolling, signing up, or otherwise agreeing to participate in the Program, you accept and
        agree to those Mobile Messaging Terms and our Privacy Policy.
      </p>

      <h2>Definitions and key terms</h2>
      <p>
        To help explain things as clearly as possible in these Terms &amp; Conditions, every time
        any of these terms are referenced, they are strictly defined as:
      </p>
      <ul>
        <li>
          <strong>Cookie:</strong> Small amount of data generated by a website and saved by your web
          browser. It is used to identify your browser, provide analytics, remember information
          about you such as your language preference or login information.
        </li>
        <li>
          <strong>Company:</strong> When these terms mention “Company,” “we,” “us,” or “our,” it
          refers to Clarky3D, that is responsible for your information under these Terms &amp;
          Conditions.
        </li>
        <li>
          <strong>Country:</strong> Where Clarky3D or the owners/founders of Clarky3D are based, in
          this case, the United States.
        </li>
        <li>
          <strong>Device:</strong> Any internet-connected device such as a phone, tablet, computer
          or any other device that can be used to visit Clarky3D and use the services.
        </li>
        <li>
          <strong>Service:</strong> Refers to the service provided by Clarky3D as described in the
          relative terms (if available) and on this platform.
        </li>
        <li>
          <strong>Website:</strong> Clarky3D’s site, which can be accessed via{" "}
          <a href="https://clarky3d.com">https://clarky3d.com</a>.
        </li>
        <li>
          <strong>You:</strong> a person or entity that is registered with Clarky3D.
        </li>
      </ul>

      <h2>Kids’ privacy</h2>
      <p>
        We do not address anyone under the age of 18. We do not knowingly collect personally
        identifiable information from anyone under the age of 18. If You are a parent or guardian
        and You are aware that Your child has provided Us with Personal Data, please contact Us. If
        We become aware that We have collected Personal Data from anyone under the age of 18 without
        verification of parental consent, We take steps to remove that information from Our servers.
      </p>

      <h2>Related policies</h2>
      <ul>
        <li>
          <Link href="/privacy">Privacy Policy</Link>
        </li>
        <li>
          <Link href="/sms-terms">SMS Terms</Link>
        </li>
      </ul>

      <h2>Contact us</h2>
      <p>Don’t hesitate to contact us if you have any questions.</p>
      <ul>
        <li>
          Via Email:{" "}
          <a href="mailto:xpozandgro@gmail.com">xpozandgro@gmail.com</a>
        </li>
        <li>
          Via Phone Number: <a href="tel:+14802576030">+1 (480) 257-6030</a>
        </li>
        <li>
          Via website: <Link href="/contact">Order / enquire</Link>
        </li>
      </ul>
      <p>
        <Link href="/">Back to home</Link>
      </p>
    </LegalArticle>
  );
}
