import Link from "next/link";
import { LegalArticle } from "@/components/legal/LegalArticle";
import { createMetadata } from "@/lib/metadata/create-metadata";

export const metadata = createMetadata({
  title: "Privacy Policy",
  description: "Clarky3D Privacy Policy — how we collect, use, and protect your information.",
  path: "/privacy",
});

export default function PrivacyPage() {
  return (
    <LegalArticle title="Privacy Policy" updated="11 August 2026">
      <p>
        Clarky3D (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy
        explains how your personal information is collected, used, and disclosed by Clarky3D.
      </p>
      <p>
        This Privacy Policy applies to our website,{" "}
        <a href="https://clarky3d.com">https://clarky3d.com</a>, and its associated subdomains
        (collectively, our “Service”).
      </p>
      <p>
        By accessing or using our Service, you signify that you have read, understood, and agree to
        our collection, storage, use, and disclosure of your personal information as described in
        this Privacy Policy and our <Link href="/terms">Terms of Service</Link>.
      </p>

      <h2>Definitions and key terms</h2>
      <p>
        To help explain things as clearly as possible in this Privacy Policy, every time any of
        these terms are referenced, they are strictly defined as:
      </p>
      <ul>
        <li>
          <strong>Cookie:</strong> A small amount of data generated by a website and saved by your
          web browser. It is used to identify your browser, provide analytics, and remember
          information about you such as your language preference or login information.
        </li>
        <li>
          <strong>Company:</strong> When this policy mentions “Company,” “we,” “us,” or “our,” it
          refers to Clarky3D, that is responsible for your information under this Privacy Policy.
        </li>
        <li>
          <strong>Country:</strong> Where Clarky3D or the owners/founders of Clarky3D are based, in
          this case the United States.
        </li>
        <li>
          <strong>Customer:</strong> Refers to the company, organization, or person that uses
          Clarky3D to manage relationships with consumers or service users.
        </li>
        <li>
          <strong>Device:</strong> Any internet-connected device such as a phone, tablet, computer,
          or any other device that can be used to visit and use the services.
        </li>
        <li>
          <strong>IP address:</strong> Every device connected to the Internet is assigned a number
          known as an Internet protocol (IP) address. These numbers are usually assigned in
          geographic blocks. An IP address can often be used to identify the location from which a
          device is connecting to the Internet.
        </li>
        <li>
          <strong>Personnel:</strong> Refers to those individuals who are employed by or are under
          contract to perform a service on behalf of one of the parties.
        </li>
        <li>
          <strong>Personal Data:</strong> Any information that directly, indirectly, or in
          connection with other information — including a personal identification number — allows
          for the identification or identifiability of a natural person.
        </li>
        <li>
          <strong>Service:</strong> Refers to the service provided by Clarky3D as described in the
          relative terms (if available) and on this platform.
        </li>
        <li>
          <strong>Website:</strong> Clarky3D’s site, which can be accessed via{" "}
          <a href="https://clarky3d.com">https://clarky3d.com</a>.
        </li>
        <li>
          <strong>You:</strong> a person or entity that is registered with Clarky3D to use the
          Services.
        </li>
      </ul>

      <h2>User consent to opt-in</h2>
      <p>
        Users opt-in by visiting <a href="https://clarky3d.com">https://clarky3d.com</a> and filling
        out their details. Users check a box to receive notifications and promotional messages to
        provide their consent. Frequency may vary. Message and data rates may apply. See our{" "}
        <Link href="/sms-terms">SMS Terms</Link> for the messaging program details.
      </p>

      <h2>What information do we collect?</h2>
      <p>
        We collect information from you when you visit our website, register on our site, place an
        order, subscribe to our newsletter, respond to a survey, or fill out a form.
      </p>
      <ul>
        <li>Name / Username</li>
        <li>Phone Numbers</li>
        <li>Email Addresses</li>
      </ul>

      <h2>Do we share the information we collect with third parties?</h2>
      <p>
        No mobile information will be shared with third parties/affiliates for marketing/promotional
        purposes. Information sharing to subcontractors in support services, such as customer
        service, is permitted. All other use case categories exclude text messaging originator
        opt-in data and consent; this information will not be shared with any third parties.
      </p>

      <h2>How do we use the information we collect?</h2>
      <p>Any of the information we collect from you may be used in one of the following ways:</p>
      <ul>
        <li>
          To personalize your experience (your information helps us to better respond to your
          individual needs)
        </li>
        <li>
          To improve our website (we continually strive to improve our website offerings based on
          the information and feedback we receive from you)
        </li>
        <li>
          To improve customer service (your information helps us to more effectively respond to your
          customer service requests and support needs)
        </li>
        <li>To process transactions</li>
        <li>To administer a contest, promotion, survey or other site feature</li>
        <li>To send periodic emails</li>
      </ul>

      <h2>How long do we keep your information?</h2>
      <p>
        We keep your information only so long as we need it to provide Clarky3D to you and fulfill
        the purposes described in this policy. When we no longer need to use your information and
        there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll
        either remove it from our systems or depersonalize it so that we can’t identify you.
      </p>

      <h2>How do we protect your information?</h2>
      <p>
        We implement a variety of security measures to maintain the safety of your personal
        information when you place an order or enter, submit, or access your personal information.
        We offer the use of a secure server. All supplied sensitive/credit information is
        transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment
        gateway providers database only to be accessible by those authorized with special access
        rights to such systems, and are required to keep the information confidential. After a
        transaction, your private information (credit cards, social security numbers, financials,
        etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of
        any information you transmit to Clarky3D or guarantee that your information on the Service
        may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical,
        technical, or managerial safeguards.
      </p>

      <h2>Is the information collected through the Service secure?</h2>
      <p>
        We take precautions to protect the security of your information. We have physical,
        electronic, and managerial procedures to help safeguard, prevent unauthorized access,
        maintain data security, and correctly use your information. However, neither people nor
        security systems are foolproof, including encryption systems. In addition, people can commit
        intentional crimes, make mistakes or fail to follow policies. Therefore, while we use
        reasonable efforts to protect your personal information, we cannot guarantee its absolute
        security. If applicable law imposes any non-disclaimable duty to protect your personal
        information, you agree that intentional misconduct will be the standards used to measure our
        compliance with that duty.
      </p>

      <h2>Can I update or correct my information?</h2>
      <p>
        The rights you have to request updates or corrections to the information Clarky3D collects
        depend on your relationship with Clarky3D. Personnel may update or correct their information
        as detailed in our internal company employment policies.
      </p>

      <h2>Personnel</h2>
      <p>
        If you are a worker or applicant, we collect information you voluntarily provide to us. We
        use the information collected for Human Resources purposes in order to administer benefits
        to workers and screen applicants. You may contact us in order to (1) update or correct your
        information, (2) change your preferences with respect to communications and other
        information you receive from us, or (3) receive a record of the information we have relating
        to you.
      </p>

      <h2>Governing law</h2>
      <p>
        This Privacy Policy is governed by the laws of the United States without regard to its
        conflict of laws provisions. You consent to the exclusive jurisdiction of the courts in
        connection with any action or dispute arising between the parties under or in connection
        with this Privacy Policy except for those individuals who may have rights to make claims
        under Privacy Shield, or the Swiss-US framework.
      </p>
      <p>
        The laws of the United States, excluding its conflicts of law rules, shall govern this
        Agreement and your use of the website. Your use of the website may also be subject to other
        local, state, national, or international laws. By using or contacting us directly, you
        signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy,
        you should not engage with our website, or use our services. Continued use of the website,
        direct engagement with us, or following the posting of changes to this Privacy Policy that
        do not significantly affect the use or disclosure of your personal information will mean
        that you accept those changes.
      </p>

      <h2>Your consent</h2>
      <p>
        We’ve updated our Privacy Policy to provide you with complete transparency into what is
        being set when you visit our site and how it’s being used. By using Clarky3D, registering an
        account, or making a purchase, you hereby consent to our Privacy Policy and agree to its
        terms.
      </p>

      <h2>Links to other websites</h2>
      <p>
        This Privacy Policy applies only to the Services. The Services may contain links to other
        websites not operated or controlled by Clarky3D. We are not responsible for the content,
        accuracy or opinions expressed in such websites, and such websites are not investigated,
        monitored or checked for accuracy or completeness by us. Please remember that when you use a
        link to go from the Services to another website, our Privacy Policy is no longer in effect.
        Your browsing and interaction on any other website, including those that have a link on our
        platform, is subject to that website’s own rules and policies.
      </p>

      <h2>Cookies</h2>
      <p>
        Clarky3D uses “Cookies” to identify the areas of our website that you have visited. A Cookie
        is a small piece of data stored on your computer or mobile device by your web browser. We
        use Cookies to enhance the performance and functionality of our website but are
        non-essential to their use. However, without these cookies, certain functionality like
        videos may become unavailable or you would be required to enter your login details every
        time you visit the website as we would not be able to remember that you had logged in
        previously. Most web browsers can be set to disable the use of Cookies. However, if you
        disable Cookies, you may not be able to access functionality on our website correctly or at
        all. We never place Personally Identifiable Information in Cookies.
      </p>

      <h2>Blocking and disabling cookies and similar technologies</h2>
      <p>
        Wherever you’re located you may also set your browser to block cookies and similar
        technologies, but this action may block our essential cookies and prevent our website from
        functioning properly, and you may not be able to fully utilize all of its features and
        services. You should also be aware that you may also lose some saved information (e.g. saved
        login details, site preferences) if you block cookies on your browser. Different browsers
        make different controls available to you. Disabling a cookie or category of cookie does not
        delete the cookie from your browser, you will need to do this yourself from within your
        browser, you should visit your browser’s help menu for more information.
      </p>

      <h2>Kids’ privacy</h2>
      <p>
        We do not address anyone under the age of 18. We do not knowingly collect personally
        identifiable information from anyone under the age of 13. If You are a parent or guardian
        and You are aware that Your child has provided Us with Personal Data, please contact Us. If
        We become aware that We have collected Personal Data from anyone under the age of 18 without
        verification of parental consent, We take steps to remove that information from Our servers.
      </p>

      <h2>Changes to our Privacy Policy</h2>
      <p>
        We may change our Service and policies, and we may need to make changes to this Privacy
        Policy so that they accurately reflect our Service and policies. Unless otherwise required
        by law, we will notify you (for example, through our Service) before we make changes to this
        Privacy Policy and give you an opportunity to review them before they go into effect. Then,
        if you continue to use the Service, you will be bound by the updated Privacy Policy. If you
        do not want to agree to this or any updated Privacy Policy, you can delete your account.
      </p>

      <h2>Information about General Data Protection Regulation (GDPR)</h2>
      <p>
        We may be collecting and using information from you if you are from the European Economic
        Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how
        and why this data is collected, and how we maintain this data under protection from being
        replicated or used in the wrong way.
      </p>
      <h3>What is GDPR?</h3>
      <p>
        GDPR is an EU-wide privacy and data protection law that regulates how EU residents’ data is
        protected by companies and enhances the control the EU residents have over their personal
        data. The GDPR is relevant to any globally operating company and not just the EU-based
        businesses and EU residents. Our customers’ data is important irrespective of where they are
        located, which is why we have implemented GDPR controls as our baseline standard for all our
        operations worldwide.
      </p>
      <h3>What is personal data?</h3>
      <p>
        Any data that relates to an identifiable or identified individual. GDPR covers a broad
        spectrum of information that could be used on its own, or in combination with other pieces
        of information, to identify a person. Personal data extends beyond a person’s name or email
        address. Some examples include financial information, political opinions, genetic data,
        biometric data, IP addresses, physical address, sexual orientation, and ethnicity.
      </p>
      <p>The Data Protection Principles include requirements such as:</p>
      <ul>
        <li>
          Personal data collected must be processed in a fair, legal, and transparent way and should
          only be used in a way that a person would reasonably expect.
        </li>
        <li>
          Personal data should only be collected to fulfil a specific purpose and it should only be
          used for that purpose. Organizations must specify why they need the personal data when
          they collect it.
        </li>
        <li>Personal data should be held no longer than necessary to fulfil its purpose.</li>
        <li>
          People covered by the GDPR have the right to access their own personal data. They can also
          request a copy of their data, and that their data be updated, deleted, restricted, or
          moved to another organization.
        </li>
      </ul>
      <h3>Why is GDPR important?</h3>
      <p>
        GDPR adds some new requirements regarding how companies should protect individuals’ personal
        data that they collect and process. It also raises the stakes for compliance by increasing
        enforcement and imposing greater fines for breach. Beyond these facts it’s simply the right
        thing to do. At Clarky3D we strongly believe that your data privacy is very important and we
        already have solid security and privacy practices in place that go beyond the requirements
        of this new regulation.
      </p>
      <h3>Individual data subject’s rights — data access, portability and deletion</h3>
      <p>
        We are committed to helping our customers meet the data subject rights requirements of GDPR.
        Clarky3D processes or stores all personal data in fully vetted, DPA compliant vendors. We do
        store all conversation and personal data for up to 6 years unless your account is deleted.
        In which case, we dispose of all data in accordance with our Terms of Service and Privacy
        Policy, but we will not hold it longer than 60 days. We are aware that if you are working
        with EU customers, you need to be able to provide them with the ability to access, update,
        retrieve and remove personal data. We’ve been set up as self service from the start and have
        always given you access to your data and your customers data. Our customer support team is
        here for you to answer any questions you might have about working with the API.
      </p>

      <h2>California residents</h2>
      <p>
        The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal
        Information we collect and how we use it, the categories of sources from whom we collect
        Personal Information.
      </p>
      <p>
        We are also required to communicate information about rights California residents have under
        California law. You may exercise the following rights:
      </p>
      <ul>
        <li>
          <strong>Right to Know and Access.</strong> You may submit a verifiable request for
          information regarding the: (1) categories of Personal Information we collect, use, (2)
          purposes for which categories of Personal Information are collected or used by us; (3)
          categories of sources from which we collect Personal Information; and (4) specific pieces
          of Personal Information we have collected about you.
        </li>
        <li>
          <strong>Right to Equal Service.</strong> We will not discriminate against you if you
          exercise your privacy rights.
        </li>
        <li>
          <strong>Right to Delete.</strong> You may submit a verifiable request to close your
          account and we will delete Personal Information about you that we have collected.
        </li>
        <li>
          Request that a business that sells a consumer’s personal data, not sell the consumer’s
          personal data.
        </li>
      </ul>
      <p>
        If you make a request, we have one month to respond to you. If you would like to exercise
        any of these rights, please contact us. We do not sell the Personal Information of our
        users. For more information about these rights, please contact us.
      </p>

      <h2>Contact us</h2>
      <p>Don’t hesitate to contact us if you have any questions.</p>
      <ul>
        <li>
          Via Email: <a href="mailto:xpozandgro@gmail.com">xpozandgro@gmail.com</a>
        </li>
        <li>
          Via Phone Number: <a href="tel:+14802576030">+1 (480) 257-6030</a>
        </li>
        <li>
          Via website: <Link href="/contact">Order / enquire</Link>
        </li>
      </ul>
      <p>
        <Link href="/">Back to home</Link>
      </p>
    </LegalArticle>
  );
}
